name: CI/CD Pipeline

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
        
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                java-version: '17'
                distribution: 'temurin'
            
            - name: Bump Version        #BREAKING CHANGE for incrementing major, feat for minor, default is patch
              id: bump
              uses: mickem/gh-action-bump-maven-version@v1.0.3
              with:
                commit: true
                push: true

            - name: Build 
              run: mvn -B package --file pom.xml

            # - name: Docker build
            #   run: docker build -t yalilila15/java-maven:${{ steps.bump.outputs.version }} .